# <u>**Part 4**



In [1]:
import numpy as np

### **Exercise 51**

The following arrays are given:

[[3, 4, 5], <br>
[8, 3, 1]] <br>

[[0, 5, 2], <br>
[4, 2, 1]] <br>

Concatenate these arrays as follows


[[3, 4, 5], <br>
[8, 3, 1], <br>
[0, 5, 2], <br>
[4, 2, 1]] <br>

In [3]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5 ,2],
              [4, 2, 1]])
C = np.concatenate((A, B), axis=0)
C

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

### **Exercise 52**

The following arrays are given:

[[4.3, 4.2], <br>
[3.1, 3.6]] <br>

[[0], <br>
[1]] <br>

Concatenate these arrays as follows

[[4.3, 4.2, 0], <br>
[3.1, 3.6, 1]] <br>


In [7]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])

array = np.concatenate((data, target), axis=1)
array

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### **Exercise 53**

The following three one-dimensional arrays are given

feature1 = np.array([1.6, 0.9, 2.2]) <br>
feature2 = np.array([0.4, 1.3, 3.2]) <br>
feature3 = np.array([1.4, 0.3, 1.2]) <br>


Transform each of these arrays into a column and concatenate them into one array

In [8]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])

In [10]:
array = np.column_stack((feature1, feature2, feature3))
array

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### **Exercise 54**

The following two-dimensional; array is given

A = np.random.randint(low=0, high=7, size=(5, 8)) <br>
A[ : , : 2] = 0 <br>
A[ : , -2 : ] = 1 <br>

Split this array into three parts

* the first two columns assign to the A1 variable
* the next four columns assign to the A2 variable
* the last two columns assign to the A3 variable



In [15]:
A = np.random.randint(low=0, high=7, size=(5, 8))
print(A, '\n')

A[:, :2] = 0
A[:, -2:] = 1
print(A)

[[6 5 5 5 0 6 0 1]
 [1 3 4 5 3 4 0 2]
 [1 4 3 0 3 1 3 4]
 [1 5 6 0 4 4 1 0]
 [2 3 1 3 0 4 3 5]] 

[[0 0 5 5 0 6 1 1]
 [0 0 4 5 3 4 1 1]
 [0 0 3 0 3 1 1 1]
 [0 0 6 0 4 4 1 1]
 [0 0 1 3 0 4 1 1]]


In [19]:
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1, '\n')
print(A2, '\n')
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]] 

[[5 5 0 6]
 [4 5 3 4]
 [3 0 3 1]
 [6 0 4 4]
 [1 3 0 4]] 

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### **Exercise 55**

The following array is given

A = np.random.randint(low=0, high=2, size=(10, 6))

Calculate the total number of non-zero elements in this array 



In [20]:
A = np.random.randint(low=0, high=2, size=(10, 6))
A

array([[1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 1, 1],
       [1, 0, 0, 0, 1, 1],
       [1, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1, 1]])

In [21]:
np.count_nonzero(A)

33

### **Exercise 56**

The following array is given

A = np.random.randn(10, 4)

et the Numpy option to print arrays with specified precision. Set precision to 4 

In [22]:
A = np.random.randn(10, 4)
A

array([[ 1.17478141, -1.03716834,  1.0383098 , -1.55080417],
       [ 0.35721789,  0.15338539,  0.67977974, -0.50418884],
       [ 0.72290838,  0.81502844,  1.55614598, -1.35648069],
       [ 0.18460702, -1.64940507, -0.94999192, -0.79193539],
       [-0.15811914,  0.05012464, -1.23241752,  2.09163225],
       [ 1.1873796 , -0.14790566,  0.10270535,  0.11360901],
       [-0.64917488,  0.78811096, -0.51585354,  0.25017288],
       [-0.8591383 , -0.70262666, -1.17930498, -0.58675023],
       [ 0.79840018,  1.87487128,  0.44105699,  1.48134764],
       [-0.35245133,  0.82849536,  0.07488328,  0.34153557]])

In [23]:
np.set_printoptions(precision=4)
A

array([[ 1.1748, -1.0372,  1.0383, -1.5508],
       [ 0.3572,  0.1534,  0.6798, -0.5042],
       [ 0.7229,  0.815 ,  1.5561, -1.3565],
       [ 0.1846, -1.6494, -0.95  , -0.7919],
       [-0.1581,  0.0501, -1.2324,  2.0916],
       [ 1.1874, -0.1479,  0.1027,  0.1136],
       [-0.6492,  0.7881, -0.5159,  0.2502],
       [-0.8591, -0.7026, -1.1793, -0.5868],
       [ 0.7984,  1.8749,  0.4411,  1.4813],
       [-0.3525,  0.8285,  0.0749,  0.3415]])

### **Exercise 57**

A = np.array([1.2e-6, 1.7e-7])

Set the precision to 8 and also set the appropriate Numpy option to suppress mathematical notation

In [25]:
A = np.array([1.2e-6, 1.7e-7])
A

array([1.2e-06, 1.7e-07])

In [26]:
np.set_printoptions(precision=8, suppress=True)
A

array([0.0000012 , 0.00000017])

### **Exercise 58**

The following array is given

A = np.random.rand(8,4)

Remove the third column

In [27]:
A = np.random.rand(8,4)
A

array([[0.950898  , 0.12091622, 0.26436229, 0.61524389],
       [0.69733367, 0.53510744, 0.49474948, 0.98943005],
       [0.42216164, 0.98257555, 0.53633031, 0.55417085],
       [0.81023347, 0.11323758, 0.21953893, 0.62224521],
       [0.57485074, 0.67754774, 0.37563173, 0.19511608],
       [0.27108547, 0.38852531, 0.84655296, 0.76169111],
       [0.71142375, 0.81670783, 0.23332228, 0.33654805],
       [0.60745296, 0.01210478, 0.10616632, 0.90768713]])

In [28]:
B = np.delete(A, [2], axis=1)
B

array([[0.950898  , 0.12091622, 0.61524389],
       [0.69733367, 0.53510744, 0.98943005],
       [0.42216164, 0.98257555, 0.55417085],
       [0.81023347, 0.11323758, 0.62224521],
       [0.57485074, 0.67754774, 0.19511608],
       [0.27108547, 0.38852531, 0.76169111],
       [0.71142375, 0.81670783, 0.33654805],
       [0.60745296, 0.01210478, 0.90768713]])

### **Exercise 59**

A one-dimensional array v (vector) is given:

v = np.array([3, 4, -2])

Calculate the norm of this vector.



In [31]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### **Exercise 60**

The following array is given

A = np.random.randint(10, size=(100, 30))

Set the Numpy option to print only ten edge elements

In [33]:
A = np.random.randint(10, size=(100, 30))
A

array([[6, 7, 5, ..., 8, 6, 7],
       [0, 4, 9, ..., 6, 2, 6],
       [3, 8, 9, ..., 7, 5, 7],
       ...,
       [1, 9, 4, ..., 9, 3, 0],
       [8, 7, 6, ..., 5, 6, 9],
       [6, 0, 1, ..., 9, 9, 7]])

In [34]:
np.set_printoptions(edgeitems=10)
A

array([[6, 7, 5, 7, 1, 6, 1, 6, 5, 9, ..., 2, 8, 6, 7, 8, 0, 1, 8, 6, 7],
       [0, 4, 9, 1, 4, 2, 3, 5, 1, 1, ..., 2, 4, 1, 3, 2, 8, 6, 6, 2, 6],
       [3, 8, 9, 3, 1, 3, 1, 6, 0, 6, ..., 8, 1, 0, 7, 4, 8, 8, 7, 5, 7],
       [2, 1, 5, 6, 2, 8, 1, 8, 3, 8, ..., 0, 0, 7, 3, 1, 1, 9, 1, 0, 7],
       [3, 4, 4, 1, 1, 5, 4, 0, 4, 4, ..., 2, 1, 5, 4, 8, 8, 9, 1, 2, 5],
       [3, 8, 3, 1, 7, 3, 8, 6, 1, 0, ..., 6, 7, 2, 3, 9, 5, 6, 1, 0, 8],
       [5, 7, 1, 5, 4, 3, 5, 4, 0, 1, ..., 8, 3, 7, 8, 8, 6, 3, 8, 4, 4],
       [5, 6, 3, 5, 5, 2, 1, 1, 9, 4, ..., 4, 6, 6, 8, 0, 0, 2, 7, 6, 3],
       [4, 0, 9, 8, 2, 7, 6, 4, 0, 9, ..., 3, 2, 0, 4, 6, 1, 8, 7, 6, 8],
       [7, 0, 7, 3, 7, 3, 8, 8, 0, 9, ..., 2, 2, 6, 6, 3, 5, 5, 5, 3, 1],
       ...,
       [4, 8, 8, 2, 3, 1, 5, 6, 1, 6, ..., 4, 1, 2, 0, 2, 0, 3, 9, 9, 1],
       [9, 2, 9, 0, 8, 7, 7, 5, 5, 6, ..., 3, 4, 3, 8, 4, 2, 9, 1, 9, 3],
       [9, 7, 9, 5, 6, 6, 8, 4, 4, 9, ..., 5, 6, 6, 6, 5, 5, 4, 3, 6, 8],
       [1, 2, 0, 9, 7, 4, 