# <u>**Part 5**<u>

In [3]:
import numpy as np

### **Exercise 41**

The following array is given

[[4, 2, 1],<br>
[6, 4, 2]],<br>

Expand this array by one dimension (add a new dimension at the beginning). Expected shape of the output array: (1, 2, 3).



In [ ]:
A = np.array([[4, 2, 1],
              [6, 4, 2],
            ])
A

array([[4, 2, 1],
       [6, 4, 2]])

In [ ]:
B = np.expand_dims(A, axis=0)
B

array([[[4, 2, 1],
        [6, 4, 2]]])

### **Exercise 42**

Using Numpy create a three-dimensional array called image with shape (200, 300, 3) filled with random values from 0 to 255 (inclusive) and data type np.uint8. Set random seed to 42.

In [2]:
np.random.seed(42)

image = np.random.randint(low = 0,
                          high=256,
                          size = (200, 300, 3),
                          dtype=np.uint8

)

image

array([[[102, 220, 225],
        [ 95, 179,  61],
        [234, 203,  92],
        ...,
        [ 41,  27,  87],
        [102, 225,  65],
        [170,   0, 238]],

       [[169, 170, 213],
        [159,  44, 250],
        [224, 206,  61],
        ...,
        [162, 118,  77],
        [228,  67,  21],
        [ 68,  30,  64]],

       [[237,  26, 118],
        [ 62, 157, 198],
        [  1, 151,  37],
        ...,
        [218, 189,  51],
        [193, 250, 243],
        [235,  34, 180]],

       ...,

       [[116, 102, 228],
        [ 29,  75,  71],
        [156, 133,  53],
        ...,
        [ 93,  45,  68],
        [124, 238,  76],
        [184, 185, 202]],

       [[216, 202, 116],
        [146, 168, 132],
        [236,  80,  45],
        ...,
        [169, 145, 212],
        [123,  50,  70],
        [ 11,  43,  62]],

       [[ 32,  52,  65],
        [155,   2,  86],
        [ 83, 240,  27],
        ...,
        [ 30,  57, 175],
        [ 72,  83, 171],
        [ 40, 114, 195]]

### **Exercise 43**

The following array is given

image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

Extend this array by one dimension (add a new dimension at the beginning) and assign to image_extended variable. Expected shape of this array is (1, 200, 300, 3).

In [5]:
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image_extended = np.expand_dims(image, axis=0)
print(image.shape)
print(image_extended.shape)

(200, 300, 3)
(1, 200, 300, 3)


### **Exercise 44**

Two randomly generated arrays are given

image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

Expand each of these arrays by adding one dimension at the beginning and then combine these arrays into one called images. Expected shape of images array: (2, 200, 300, 3).



In [7]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image1_ext = np.expand_dims(image1, axis=0)
image2_ext = np.expand_dims(image2, axis=0)

images = np.concatenate((image1_ext, image2_ext), axis=0)

print(image1_ext.shape)
print(image2_ext.shape)
print(images.shape)

(1, 200, 300, 3)
(1, 200, 300, 3)
(2, 200, 300, 3)


### **Exercise 45**

[[[1, 2, 3],<br>
[6, 3, 2]]]

Shape of this array is (1, 2, 3). Remove the unnecessary first dimension and extract the (2, 3) array

In [9]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])

B = np.squeeze(A, axis=0)
print(A.shape)
print(B.shape)

(1, 2, 3)
(2, 3)


### **Exercise 46**

The following array is given

[[0.4], <br>
[0.9], <br>
[0.5], <br>
[0.6]] <br>

Shape of this array is (4, 1). Remove the unnecessary dimension and extract (4, ) array and print result to the console.



In [10]:
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])

B=np.squeeze(A, axis=1)
print(A.shape)
print(B.shape)

(4, 1)
(4,)


### **Exercise 47**

The following array is given

[[ 0,  1,  2,  3], <br>
[ 4,  5,  6,  7], <br>
[ 8,  9, 10, 11]] <br>

Using the slice operator, transform this array into the following

[[ 3,  2,  1,  0], <br>
[ 7,  6,  5,  4], <br>
[11, 10,  9,  8]] <br>

In [4]:
A = np.arange(12, dtype='int').reshape(-1, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
A[:, ::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

### **Exercise 48**

The following array is given

[[ 0,  1,  2,  3], <br>
[ 4,  5,  6,  7], <br>
[ 8,  9, 10, 11]] <br>

Using the slice operator, transform this array into the following

[[ 11,  10,  9,  8], <br>
[ 7,  6,  5,  4], <br>
[3, 2,  1,  0]] <br>

In [6]:
A = np.arange(12, dtype='int').reshape(-1, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
A[::-1, ::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### **Exercise 49**

Random seed is set to 42. The following array is given:

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

Extract the first channel (index 0) of this image array and print it to the console.

In [11]:
np.random.seed(42)
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

print(image)

print(image[:, :, 0])

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  [  3  98 243]
  [ 14 149 245]
  [ 46 106 244]
  [ 99 187  71]
  [212 153 199]
  [188 174  65]
  [153  20  44]]

 [[203 152 102]
  [214 240  39]
  [121  24  34]
  [114 210  65]
  [239  39 214]
  [244 151  25]
  [ 74 145 222]
  [ 14 202  85]
  [145 117  87]
  [184 189 221]]

 [[116 237 109]
  [ 85  99 172]
  [226 153 103]
  [235 146  36]
  [151  62  68]
  [181 130 160]
  [160 166 149]
  [  6  69   5]
  [ 52 253 112]
  [ 14   1   3]]

 [[ 76 248  87]
  [233 212 184]
  [235 245  26]
  [213 157 253]
  [ 68 240  37]
  [219  91  54]
  [129   9  51]
  [  0 191  20]
  [140  46 187]
  [147   1 254]]

 [[ 20 153 243]
  [ 46 160  68]
  [ 19 158 203]
  [209 226  77]
  [ 57  77 149]
  [156  21 112]
  [ 86 134 252]
  [ 24 207   1]
  [235 242 147]
  [110  88 107]]

 [[231   5  48]
  [254 141  74]
  [218 161  87]
  [134  58 100]
  [162 156 254]
  [ 73  93 102]
  [169 222 181]
  [ 35 255  71]
  [242  11 219]
  [253 201  74]]

 [[187  10  72]
  [249 207 2

### **Exercise 50**

The following array is given

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

Extract any array of shape (5, 5, 3) from this array and assign to the result variable.



In [17]:
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
result = image[:5, :5, :]
result

array([[[ 28, 210, 251],
        [ 51,  35, 132],
        [146,  58,  12],
        [218,  94, 241],
        [159, 244, 180]],

       [[ 69,  41,  27],
        [ 87, 102, 225],
        [ 65, 170,   0],
        [238, 169, 170],
        [213, 159,  44]],

       [[133,  10,  24],
        [223,  27, 115],
        [223, 116,  27],
        [116, 189, 205],
        [107, 182, 235]],

       [[ 30, 226,  74],
        [ 85,  18, 138],
        [127,  70,   8],
        [ 83, 249, 101],
        [180, 206, 246]],

       [[189, 232,  37],
        [232, 224,  92],
        [ 44,  28, 128],
        [117, 170,  69],
        [120, 245,  89]]], dtype=uint8)