# <u>**Part 10**

In [1]:
import numpy as np

### **Exercise 91**

The following string is given (WIG.GAMES index data):

wig_games_raw = """Profile    Time    Course    Change    Change%    Ref.    Open    Low    High    Volume    Turn    Share <br>
11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034% <br>
CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618% <br>
CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855% <br>
PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638% <br>
TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%"""

Create an array from this string and assign to the wig_games variable

In [ ]:
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""

In [ ]:
lines = wig_games_raw.splitlines()
lines

['Profile\tTime\tCourse\tChange\tChange%\tRef.\tOpen\tLow\tHigh\tVolume\tTurn\tShare',
 '11B (11BIT)\t17 kwi 17:01\t391.00\t+8.00\t(+2.09%)\t383.00\t383.50\t383.00\t394.00\t12 784\t4 994 874\t19.034%',
 'CDR (CDPROJEKT)\t17 kwi 17:01\t339.50\t+5.30\t(+1.59%)\t334.20\t338.30\t337.00\t344.20\t233 059\t79 245 368\t39.618%',
 'CIG (CIGAMES)\t17 kwi 17:03\t0.742\t-0.012\t(-1.59%)\t0.754\t0.772\t0.730\t0.772\t1 311 078\t971 459\t1.855%',
 'PLW (PLAYWAY)\t17 kwi 17:03\t387.50\t+18.00\t(+4.87%)\t369.50\t374.00\t373.00\t388.00\t33 206\t12 661 786\t10.638%',
 'TEN (TSGAMES)\t17 kwi 17:02\t349.50\t+22.50\t(+6.88%)\t327.00\t332.00\t330.00\t353.50\t39 793\t13 697 060\t28.855%']

In [ ]:
lines = [line.split('\t') for line in lines]
lines

[['Profile',
  'Time',
  'Course',
  'Change',
  'Change%',
  'Ref.',
  'Open',
  'Low',
  'High',
  'Volume',
  'Turn',
  'Share'],
 ['11B (11BIT)',
  '17 kwi 17:01',
  '391.00',
  '+8.00',
  '(+2.09%)',
  '383.00',
  '383.50',
  '383.00',
  '394.00',
  '12 784',
  '4 994 874',
  '19.034%'],
 ['CDR (CDPROJEKT)',
  '17 kwi 17:01',
  '339.50',
  '+5.30',
  '(+1.59%)',
  '334.20',
  '338.30',
  '337.00',
  '344.20',
  '233 059',
  '79 245 368',
  '39.618%'],
 ['CIG (CIGAMES)',
  '17 kwi 17:03',
  '0.742',
  '-0.012',
  '(-1.59%)',
  '0.754',
  '0.772',
  '0.730',
  '0.772',
  '1 311 078',
  '971 459',
  '1.855%'],
 ['PLW (PLAYWAY)',
  '17 kwi 17:03',
  '387.50',
  '+18.00',
  '(+4.87%)',
  '369.50',
  '374.00',
  '373.00',
  '388.00',
  '33 206',
  '12 661 786',
  '10.638%'],
 ['TEN (TSGAMES)',
  '17 kwi 17:02',
  '349.50',
  '+22.50',
  '(+6.88%)',
  '327.00',
  '332.00',
  '330.00',
  '353.50',
  '39 793',
  '13 697 060',
  '28.855%']]

In [ ]:
wig_games = np.array(lines, dtype=str)
wig_games

array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B (11BIT)', '17 kwi 17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12 784', '4 994 874', '19.034%'],
       ['CDR (CDPROJEKT)', '17 kwi 17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233 059', '79 245 368', '39.618%'],
       ['CIG (CIGAMES)', '17 kwi 17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1 311 078', '971 459', '1.855%'],
       ['PLW (PLAYWAY)', '17 kwi 17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33 206', '12 661 786', '10.638%'],
       ['TEN (TSGAMES)', '17 kwi 17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39 793', '13 697 060', '28.855%']],
      dtype='<U15')

In [ ]:
wig_games = np.char.replace(wig_games, ' ', '')
wig_games

array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')

### **Exercise 92**

The following array is given

wig_games = np.array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'], <br>
['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'], <br>
['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'], <br>
['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'], <br>
['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'], <br>
['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')

Remove the following columns

* Change
* Change%
* Ref
* Volume



In [ ]:
wig_games = np.array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')

In [ ]:
wig_games = np.delete(wig_games, [3, 4, 5, 9], axis=1)
wig_games

array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')

### **Exercise 93**

The follwowing array is given


wig_games = np.array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'], <br>
['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'], <br>
['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'], <br>
['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'], <br>
['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'], <br>
['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')

Save this array to the 'wig_games.csv' file. Then load the content of this file into the wig_games_new variable


In [ ]:
wig_games = np.array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')

In [ ]:
np.savetxt(fname='wig_games.csv', X=wig_games, fmt='%s', delimiter=',')

In [ ]:
wig_games_new = np.loadtxt(
    fname='wig_games.csv', 
    delimiter=',', 
    dtype=str)

wig_games_new

array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')

### **Exercise 94**

The following string is given (Playway's March 2020 listings):

playway_raw = """Date,Open,High,Low,Close,Volume <br>
2020-03-02,305,324.5,283.5,310,64081 <br>
2020-03-03,325.5,340.5,320,340.5,55496 <br>
2020-03-04,324,340.5,315,330,36152 <br>
2020-03-05,344,344,310,315,35992 <br>
2020-03-06,306.5,307,291,305,32539 <br>
2020-03-09,274,291,250,258,79402 <br>
2020-03-10,278,284.5,256,264,35700 <br>
2020-03-11,270,270,238.5,245,60445 <br>
2020-03-12,218,228,196,197,94031 <br>
2020-03-13,210,229,198.8,211,100412 <br>
2020-03-16,205,248,197.8,240.5,50659 <br>
2020-03-17,245,269,232.5,264,99480 <br>
2020-03-18,264,280,251,270,70136 <br>
2020-03-19,267,280,267,279.5,30732 <br>
2020-03-20,297.5,307,280,280.5,43426 <br>
2020-03-23,274,289,258,285,37098 <br>
2020-03-24,305,309,296.5,309,31939 <br>
2020-03-25,313,330,295,304,46724 <br>
2020-03-26,300,309,295.5,300,27213 <br>
2020-03-27,302,306.5,290,296,13466 <br>
2020-03-30,299,300,287,300,10316 <br>
2020-03-31,302.5,309,302,306.5,15698"""

Create an array from this string and assign to the *playway* variable

In [ ]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

In [ ]:
lines = playway_raw.splitlines()
lines = [line.split(',') for line in lines]
playway = np.array(lines, dtype=str)
print(playway)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

### **Exercise 95**

The following array is given

playway = np.array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'], <br>
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'], <br>
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'], <br>
       ['2020-03-04', '324', '340.5', '315', '330', '36152'], <br>
       ['2020-03-05', '344', '344', '310', '315', '35992'], <br>
       ['2020-03-06', '306.5', '307', '291', '305', '32539'], <br>
       ['2020-03-09', '274', '291', '250', '258', '79402'], <br>
       ['2020-03-10', '278', '284.5', '256', '264', '35700'], <br>
       ['2020-03-11', '270', '270', '238.5', '245', '60445'], <br>
       ['2020-03-12', '218', '228', '196', '197', '94031'], <br>
       ['2020-03-13', '210', '229', '198.8', '211', '100412'], <br>
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'], <br>
       ['2020-03-17', '245', '269', '232.5', '264', '99480'], <br>
       ['2020-03-18', '264', '280', '251', '270', '70136'], <br>
       ['2020-03-19', '267', '280', '267', '279.5', '30732'], <br>
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'], <br>
       ['2020-03-23', '274', '289', '258', '285', '37098'], <br>
       ['2020-03-24', '305', '309', '296.5', '309', '31939'], <br>
       ['2020-03-25', '313', '330', '295', '304', '46724'], <br>
       ['2020-03-26', '300', '309', '295.5', '300', '27213'], <br>
       ['2020-03-27', '302', '306.5', '290', '296', '13466'], <br>
       ['2020-03-30', '299', '300', '287', '300', '10316'], <br>
       ['2020-03-31', '302.5', '309', '302', '306.5', '15698']],<br>
      dtype='<U10')

Delete the 'Date' column. Then remove the headers and assign result to the playway_values variable. Convert this array to the float data type

In [2]:
playway = np.array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
       ['2020-03-23', '274', '289', '258', '285', '37098'],
       ['2020-03-24', '305', '309', '296.5', '309', '31939'],
       ['2020-03-25', '313', '330', '295', '304', '46724'],
       ['2020-03-26', '300', '309', '295.5', '300', '27213'],
       ['2020-03-27', '302', '306.5', '290', '296', '13466'],
       ['2020-03-30', '299', '300', '287', '300', '10316'],
       ['2020-03-31', '302.5', '309', '302', '306.5', '15698']],
      dtype='<U10')

In [3]:
playway = np.delete(playway, [0], axis=1)
playway_values = playway[1:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

### **Exercise 96**

The following array is given (*float* type):

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],<br>
       [   325.5,    340.5,    320. ,    340.5,  55496. ], <br>
       [   324. ,    340.5,    315. ,    330. ,  36152. ], <br>
       [   344. ,    344. ,    310. ,    315. ,  35992. ], <br>
       [   306.5,    307. ,    291. ,    305. ,  32539. ], <br>
       [   274. ,    291. ,    250. ,    258. ,  79402. ], <br>
       [   278. ,    284.5,    256. ,    264. ,  35700. ], <br>
       [   270. ,    270. ,    238.5,    245. ,  60445. ], <br>
       [   218. ,    228. ,    196. ,    197. ,  94031. ], <br>
       [   210. ,    229. ,    198.8,    211. , 100412. ], <br>
       [   205. ,    248. ,    197.8,    240.5,  50659. ], <br>
       [   245. ,    269. ,    232.5,    264. ,  99480. ], <br>
       [   264. ,    280. ,    251. ,    270. ,  70136. ], <br>
       [   267. ,    280. ,    267. ,    279.5,  30732. ], <br>
       [   297.5,    307. ,    280. ,    280.5,  43426. ], <br>
       [   274. ,    289. ,    258. ,    285. ,  37098. ], <br>
       [   305. ,    309. ,    296.5,    309. ,  31939. ], <br>
       [   313. ,    330. ,    295. ,    304. ,  46724. ], <br>
       [   300. ,    309. ,    295.5,    300. ,  27213. ], <br>
       [   302. ,    306.5,    290. ,    296. ,  13466. ], <br>
       [   299. ,    300. ,    287. ,    300. ,  10316. ], <br>
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])



Calculate the average value for each column. Round the result to two decimal places

In [4]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])


In [5]:
np.round(playway_values.mean(axis=0), 2)

array([  283.14,   295.25,   268.69,   282.3 , 48688.05])

### **Exercise 97**

The following array is given

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ], <br>
       [   325.5,    340.5,    320. ,    340.5,  55496. ], <br>
       [   324. ,    340.5,    315. ,    330. ,  36152. ], <br>
       [   344. ,    344. ,    310. ,    315. ,  35992. ], <br>
       [   306.5,    307. ,    291. ,    305. ,  32539. ], <br>
       [   274. ,    291. ,    250. ,    258. ,  79402. ], <br>
       [   278. ,    284.5,    256. ,    264. ,  35700. ], <br>
       [   270. ,    270. ,    238.5,    245. ,  60445. ], <br>
       [   218. ,    228. ,    196. ,    197. ,  94031. ], <br>
       [   210. ,    229. ,    198.8,    211. , 100412. ], <br>
       [   205. ,    248. ,    197.8,    240.5,  50659. ], <br>
       [   245. ,    269. ,    232.5,    264. ,  99480. ], <br>
       [   264. ,    280. ,    251. ,    270. ,  70136. ], <br>
       [   267. ,    280. ,    267. ,    279.5,  30732. ], <br>
       [   297.5,    307. ,    280. ,    280.5,  43426. ], <br>
       [   274. ,    289. ,    258. ,    285. ,  37098. ], <br>
       [   305. ,    309. ,    296.5,    309. ,  31939. ], <br>
       [   313. ,    330. ,    295. ,    304. ,  46724. ], <br>
       [   300. ,    309. ,    295.5,    300. ,  27213. ], <br>
       [   302. ,    306.5,    290. ,    296. ,  13466. ], <br>
       [   299. ,    300. ,    287. ,    300. ,  10316. ], <br>
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])


Add a new column which shows the difference between higghest and lowest price.

* First assign the calculated difference to the max_min_diff variable
* Then add the calculated column (variable max_min_diff) to the playway_values array




In [8]:
np.set_printoptions(suppress=True)

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])

In [9]:
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

### **Exercise 98**

The following array is given

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ], <br>
       [   325.5,    340.5,    320. ,    340.5,  55496. ], <br>
       [   324. ,    340.5,    315. ,    330. ,  36152. ], <br>
       [   344. ,    344. ,    310. ,    315. ,  35992. ], <br>
       [   306.5,    307. ,    291. ,    305. ,  32539. ], <br>
       [   274. ,    291. ,    250. ,    258. ,  79402. ], <br>
       [   278. ,    284.5,    256. ,    264. ,  35700. ], <br>
       [   270. ,    270. ,    238.5,    245. ,  60445. ], <br>
       [   218. ,    228. ,    196. ,    197. ,  94031. ], <br>
       [   210. ,    229. ,    198.8,    211. , 100412. ], <br>
       [   205. ,    248. ,    197.8,    240.5,  50659. ], <br>
       [   245. ,    269. ,    232.5,    264. ,  99480. ], <br>
       [   264. ,    280. ,    251. ,    270. ,  70136. ], <br>
       [   267. ,    280. ,    267. ,    279.5,  30732. ], <br>
       [   297.5,    307. ,    280. ,    280.5,  43426. ], <br>
       [   274. ,    289. ,    258. ,    285. ,  37098. ], <br>
       [   305. ,    309. ,    296.5,    309. ,  31939. ], <br>
       [   313. ,    330. ,    295. ,    304. ,  46724. ], <br>
       [   300. ,    309. ,    295.5,    300. ,  27213. ], <br>
       [   302. ,    306.5,    290. ,    296. ,  13466. ], <br>
       [   299. ,    300. ,    287. ,    300. ,  10316. ], <br>
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])

Extract rows from this array where closing price (column with index 3) is greater than 300.0

In [10]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

In [14]:
playway_values[playway_values[:, 3] > 300.0]

array([[  305. ,   324.5,   283.5,   310. , 64081. ,    41. ],
       [  325.5,   340.5,   320. ,   340.5, 55496. ,    20.5],
       [  324. ,   340.5,   315. ,   330. , 36152. ,    25.5],
       [  344. ,   344. ,   310. ,   315. , 35992. ,    34. ],
       [  306.5,   307. ,   291. ,   305. , 32539. ,    16. ],
       [  305. ,   309. ,   296.5,   309. , 31939. ,    12.5],
       [  313. ,   330. ,   295. ,   304. , 46724. ,    35. ],
       [  302.5,   309. ,   302. ,   306.5, 15698. ,     7. ]])

### **Exercise 99**

The following array is given

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ], <br>
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5], <br>
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5], <br>
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ], <br>
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ], <br>
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ], <br>
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5], <br>
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5], <br>
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ], <br>
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2], <br>
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2], <br>
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5], <br>
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ], <br>
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ], <br>
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ], <br>
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ], <br>
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5], <br>
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ], <br>
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5], <br>
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5], <br>
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ], <br>
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

From this array extract the first 10 rows with the highest volume sorted in descending order.

In [15]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

In [16]:
playway_values[playway_values[:, 4].argsort()[::-1]][:10]

array([[   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ]])

### **Exercise 100**

playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ], <br>
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5], <br>
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5], <br>
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ], <br>
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ], <br>
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ], <br>
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5], <br>
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5], <br>
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ], <br>
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2], <br>
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2], <br>
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5], <br>
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ], <br>
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ], <br>
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ], <br>
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ], <br>
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5], <br>
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ], <br>
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5], <br>
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5], <br>
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ], <br>
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

Add to this array column that returns 1 in case the close price is higher than the open price, otherwise 0.


In [17]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
       [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
       [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
       [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
       [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
       [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
       [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
       [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
       [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
       [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
       [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])

In [18]:
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

### **Exercise 101**

Solve the following system of equations

$5x - 3y = 21$ <br>
$x - 2y =7$



In [19]:
A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
print(f'x = {x:.2f}\ny = {y:.2f}')

x = 3.00
y = -2.00


### **Exercise 102**

Solve the following system of equations

$x + y + z = 1$ <br>
$2x + y + 5z = 0$ <br>
$x - y = z$ 




In [20]:
A = np.array([[1, 1, 1], [2, 1, 5], [1, -1, -1]])
B = np.array([[1], [0], [0]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
z = X[2][0]
print(f'x = {x:.2f}\ny = {y:.2f}\nz = {z:.2f}')

x = 0.50
y = 0.88
z = -0.38
