# <u>**Part 7**



In [1]:
import numpy as np

### **Exercise 61**

The followings arrays are given

[[3, 4, 9, 2],<br>
[5, 3, 2, 5]]<br>

[[4, 3, 2, 5], <br>
[6, 3, 1, 6]]

Calculate arithmetic means of these arrays (elementwise) 

In [4]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

print((A+B)/2, '\n')
print(np.divide(np.add(A,B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]] 

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


### **Exercise 62**

The following arrays are given


[[3, 4, 9, 2],<br>
[5, 3, 2, 5]]<br>

[[4, 3, 2, 5], <br>
[6, 3, 1, 6]]

Multiply these arrays (elementwise).

In [8]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])

print((A*B), '\n')
print(np.multiply(A, B))

[[12 12 18 10]
 [30  9  2 30]] 

[[12 12 18 10]
 [30  9  2 30]]


### **Exercise 63**

The following array is given

[[3, 4, 9, 2],<br>
[5, 3, 2, 5]]<br>

Calculate the square root of each element of this array

In [9]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])

np.sqrt(A)

array([[1.73205081, 2.        , 3.        , 1.41421356],
       [2.23606798, 1.73205081, 1.41421356, 2.23606798]])

### **Exercise 64**

The following arrays are given

A = np.linspace(0, np.pi / 2, 20) <br>
B = np.full(shape=(20,), fill_value=1, dtype='float')

Check the Pythagorean formula for sines and cosines on the A array and then compare the result with the B array. Use the np.allclose() function in this exercise.

In [11]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')

print(A)
print(B)

[0.         0.08267349 0.16534698 0.24802047 0.33069396 0.41336745
 0.49604095 0.57871444 0.66138793 0.74406142 0.82673491 0.9094084
 0.99208189 1.07475538 1.15742887 1.24010236 1.32277585 1.40544935
 1.48812284 1.57079633]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [12]:
np.allclose(np.sin(A)**2+ np.cos(A)**2, B)

True

In [13]:
np.allclose(np.power(np.sin(A), 2)+ np.power(np.cos(A), 2), B)

True

### **Exercise 65**

The following arrays are given:

[[2, 3], <br>
[-4, 2], <br>
[5, 0]]

[[4, 3, 2], <br>
[-1, 0, 2]]

Shapes of these arrays
* A - 3x2
* B - 2x3

Perform matrix multiplication A*B 



In [15]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])

B = np.array([[4, 3, 2],
              [-1, 0, 2]])

np.dot(A, B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### **Exercise 66**

The following array (square matrix) is given

[[-2, 0, 4], <br>
[5, 2, -1], <br>
[-4, 2, 4], <br>

Calculate the determinant of this matrix and print it to the console

In [16]:
A = np.array([[-2, 0, 4],
              [5, 2, 1],
              [-4, 2, 4]])

In [17]:
np.linalg.det(A)

59.999999999999986

### **Exercise 67**

The following array (square matrix) is given

[[5, 8, 16], <br>
[4, 1, 8], <br>
[-4, 4, -11]]

Calculate eigenvalues and their corresponding eigenvectors of this matrix

In [18]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

In [20]:
np.linalg.eig(A)

(array([-9.24621125, -3.        ,  7.24621125]),
 array([[-6.26164716e-01, -8.94427191e-01,  8.90159406e-01],
        [-3.13082358e-01,  2.82399734e-16,  4.45079703e-01],
        [ 7.14070855e-01,  4.47213595e-01, -9.75719719e-02]]))

In [21]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


### **Exercise 68**

The following array (square matrix) is given:

[[5, 8, 16], <br>
[4, 1, 8], <br>
[-4, 4, -11]]

Find the inverse to this matrix


In [22]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

np.linalg.inv(A)

array([[-0.21393035,  0.75621891,  0.23880597],
       [ 0.05970149,  0.04477612,  0.11940299],
       [ 0.09950249, -0.25870647, -0.13432836]])

### **Exercise 69**

The following array (square matrix) is given:

[[5, 8, 16], <br>
[4, 1, 8], <br>
[-4, 4, -11]]

Find the trace of this matrix (sum of elements on the main diagonal).

In [23]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])

np.trace(A)

-5

### **Exercise 70**

The following arrays are given

[[2, 0], <br>
[4, 2], <br>
[5, 3], <br>
[4, 2], <br>


[[4, 0, 2, 1, 1, 0, 2, 9]]

Shapes of the arrays

* A - 4x2
* B - 1x8

Transform B array to perform the matrix multiplication A x B. Then perform this multiplication

In [27]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

np.dot(A, B.reshape(2, -1))

array([[ 8,  0,  4,  2],
       [18,  0, 12, 22],
       [23,  0, 16, 32],
       [18,  0, 12, 22]])