# <u>**Part 1**

In [16]:
import numpy as np

### **Exercise 1**


Check if all elements from the following array return the logical value True:

In [17]:
A = np.array([[3, 2, 1, 4],
             [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
             [5, 2, 0, 6]])

C = ([[True, False, False],
      [True, True, False]])

D = np.array([0.1, 0.3])

In [18]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


### **Exercise 2**


Check if all elements from the following arrays return the logical value *True* along with *index 1*:

In [19]:
A = np.array([[3, 2, 1, 4],
             [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
             [5, 2, 0, 6]])

C = ([[True, False, False],
      [True, True, False]])

In [20]:
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False False]


### **Exercise 3**



Check if *any* element of the following arrays returns the logical value True:

In [21]:
A = np.array([[3, 2, 1, 4],
             [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
             [5, 2, 0, 6]])

C = ([[True, False, False],
      [True, True, False]])

D = np.array([0.1, 0.3])

In [22]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: True
B: True
C: True
D: True


### **Exercise 4**

Check if any element of the following arrays returns the logical value True along the axis with *index 0*:

In [23]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])

In [24]:
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


### **Exercise 5**

Check if the following array has missing data

In [25]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])

In [26]:
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

### **Exercise 6**

Check if the following arrays are equal (element-wise):

In [27]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

In [28]:
np.allclose(A,B)

True

### **Exercise 7**

Check if the following arrays are equal (element-wise):

In [29]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

In [30]:
# method 1
A == B

array([False, False,  True])

In [31]:
# method 2
np.equal(A, B)

array([False, False,  True])

### **Exercise 8**

Check which numbers (element-wise) from the A array are greater than numbers from the B array and print result to the console as shown below.

In [32]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

In [33]:
# method 1
np.greater(A,B)

array([ True, False, False, False])

In [34]:
# method 2
A > B

array([ True, False, False, False])

### **Exercise 9**

Using Numpy create a 4x4 array filled with zeros (set data type to int)

In [35]:
array = np.zeros((4,4), dtype=int)
array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### **Exercise 10**

Using Numpy, create an array 10x10 filled with number 255 and set the data type to float

In [36]:
# method 1
np.full((10,10), 255, dtype=float)

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])

In [37]:
# method 2
np.ones((10,10), dtype=float) * 255

array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])