# <u>**Part 8**

In [2]:
import numpy as np

### **Exercise 71**

The following array is given

[['id', 'price'], <br>
['001', 14.99], <br>
['002', 4.99], <br>
['003', 7.99], <br>
['004', 2.49], <br>
['005', 1.49]]

Starting with the second row of this array, randomly shuffle the rows 

In [10]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
A

array([['id', 'price'],
       ['001', '14.99'],
       ['002', '4.99'],
       ['003', '7.99'],
       ['004', '2.49'],
       ['005', '1.49']], dtype='<U32')

In [11]:
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['005', '1.49'],
       ['004', '2.49'],
       ['001', '14.99'],
       ['002', '4.99'],
       ['003', '7.99']], dtype='<U32')

### **Exercise 72**

The following array is given

[0.2, 0.15, 0.1, 0.3, 0.2, 0.05]

Return a list on indexes that sirts this array in asceding order

In [12]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])

print(np.argsort(A))

[5 2 1 0 4 3]


### **Exercise 73**

The following array is given

A = np.random.randn(10, 8)

Round the values of this array to three decimal places


In [13]:
A = np.random.randn(10, 8)
A

array([[-2.13508345,  1.22701989,  1.00498287, -0.59314313, -0.03668155,
         3.25076782,  0.29244203, -0.8428345 ],
       [-0.70794142, -0.58891136,  0.14791325,  0.72161386, -1.32172219,
         2.18151182,  0.97993691,  2.34659552],
       [ 0.58779506,  0.2358804 , -0.41314624,  1.69625813, -1.02085176,
        -0.34783895,  0.85352437,  0.29275662],
       [-1.04601176,  0.42493195, -0.52275927,  0.1317998 , -0.81068845,
        -0.08111142,  1.95752829,  1.75854324],
       [ 0.79292331, -1.00239065,  1.65838922, -0.5363145 , -0.93099769,
        -0.62485196,  0.62520426,  0.19527311],
       [ 3.44760781, -0.23873964,  0.06476723,  0.69992377,  0.21124865,
        -1.61559516,  1.19132067,  0.18345005],
       [-0.20094928, -0.480315  , -0.03060424, -1.24464539,  1.00790365,
         0.26113881, -0.04574916, -1.2049382 ],
       [-0.22575945, -1.32483082,  1.23232849,  0.0356693 ,  1.46772293,
         0.9599414 ,  2.77107289,  0.51430692],
       [-1.89237389, -0.26417846

In [14]:
np.round(A, 3)

array([[-2.135,  1.227,  1.005, -0.593, -0.037,  3.251,  0.292, -0.843],
       [-0.708, -0.589,  0.148,  0.722, -1.322,  2.182,  0.98 ,  2.347],
       [ 0.588,  0.236, -0.413,  1.696, -1.021, -0.348,  0.854,  0.293],
       [-1.046,  0.425, -0.523,  0.132, -0.811, -0.081,  1.958,  1.759],
       [ 0.793, -1.002,  1.658, -0.536, -0.931, -0.625,  0.625,  0.195],
       [ 3.448, -0.239,  0.065,  0.7  ,  0.211, -1.616,  1.191,  0.183],
       [-0.201, -0.48 , -0.031, -1.245,  1.008,  0.261, -0.046, -1.205],
       [-0.226, -1.325,  1.232,  0.036,  1.468,  0.96 ,  2.771,  0.514],
       [-1.892, -0.264, -1.112, -2.224,  0.196, -2.167,  1.284,  0.951],
       [-2.12 , -0.332,  0.565,  1.132,  0.594, -0.386,  0.541, -0.852]])

### **Exercise 74**

calculate the roots of the following polynomial

$w(x) = 4x^2 + 5x + 1$


In [16]:
w = np.array([4, 5, 1])
np.roots(w)

array([-1.  , -0.25])

### **Exercise 75**

calculate the roots of the following polynomials

$Q(x) = 2x^3 + 4x^2 - 5x +1 $ <br>
$R(x) = 2x^3 - 5x +1 $




In [18]:
q = np.array([2, 4, -5, 1])
r = np.array([2, 0, -5, 1])

print(np.roots(q))
print(np.roots(r))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


### **Exercise 76**

The following polynomials are given

$W(x) = 4x^2 + 5x +1 $ <br>
$Q(x) = 2x^3 + 4x^2 - 5x +1 $

perform the following operations

$W(x) + Q(x)$ <br>
$W(x) - Q(x)$ <br>
$W(x) * Q(x)$ <br>
$W(x) + 2Q(x)$ 


In [19]:
w = np.array([4, 5, 1])
q = np.array([2, 4, -5, 1])

print(np.polyadd(w, q))
print(np.polysub(w, q))
print(np.polymul(w, q))
print(np.polyadd(w, 2*q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


### **Exercise 77**

The following array is given

[[-4, 3, 0, 1, -5], <br>
[6, -4, -2, 1 , 3]]

Use the sign function for this array


In [22]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])

np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### **Exercise 78**

Using the np.arange() function, generate the following array

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05' <br>
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10' <br>
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15' <br>
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20' <br>
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25' <br>
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30' <br>
 '2021-01-31']

In [23]:
A = np.arange('2021-01-01', '2021-02-01', dtype= 'datetime64[D]')
A

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

### **Exercise 79**

Using the np.arange() function, generate the following array

[['2021-01' '2021-02' '2021-03'] <br>
 ['2021-04' '2021-05' '2021-06'] <br>
 ['2021-07' '2021-08' '2021-09'] <br>
 ['2021-10' '2021-11' '2021-12']]

In [24]:
A = np.arange('2021-01', '2022-01', dtype='datetime64[M]')
A = A.reshape(-1, 3)
print(A)

[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]


### **Exercise 80**

Using the np.datetime64() function, generate today's date

In [25]:
np.datetime64('today')

numpy.datetime64('2022-09-29')