# <u>**Part 3**

In [1]:
import numpy as np

### **Exercise 21**

Using Numpy create the following array:

[[ 0,  1,  2,  3],<br>
[ 4,  5,  6,  7],<br>
[ 8,  9, 10, 11]]

Save this array to a binary file named 'array.npy' and then load that file back into another variable.

In [7]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
A = np.arange(0,12).reshape(3,4)
np.save('array.npy', A)

In [9]:
B = np.load('array.npy')
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### **Exercise 22**

Using Numpy create the following array:

[[ 0,  1,  2,  3],<br>
[ 4,  5,  6,  7],<br>
[ 8,  9, 10, 11]]

Save this array to a text file named 'array.txt' with two decimal places and then load this file back into another variable. 

In [10]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
A = np.arange(0,12).reshape(3,4)
np.savetxt('array.txt', A)

In [16]:
B = np.loadtxt('array.txt')
B

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

### **Exercise 23**

Using Numpy create and convert the following array into the list:

[[ 0,  1,  2,  3],<br>
[ 4,  5,  6,  7],<br>
[ 8,  9, 10, 11]]


In [17]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
B = A.tolist()
B

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### **Exercise 24**

The following array is given:

[[ 0,  1,  2,  3],<br>
[ 4,  5,  6,  7],<br>
[ 8,  9, 10, 11]] <br>

Using the slice operator, transform this array into the following:

[[ 8,  9,  10,  11],<br>
[ 4,  5,  6,  7],<br>
[ 0,  1, 2, 3]] <br>

In [21]:
A = np.arange(0,12).reshape(3,4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
A[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### **Exercise 25**

Transform the following array

[[ 1, 1, 1, 1],<br>
[ 1, 1, 1, 1],<br>
[ 1, 1, 1, 1]<br>
[ 1, 1, 1, 1]] <br>

To the following array

[[0, 0, 0, 0, 0, 0],<br>
[ 0, 1, 1, 1, 1, 0],<br>
[ 0, 1, 1, 1, 1, 0],<br>
[ 0, 1, 1, 1, 1, 0],<br>
[ 0, 1, 1, 1, 1, 0],<br>
[ 0, 0, 0, 0, 0, 0]] <br>


In [24]:
A = np.ones(shape=(4,4))
A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
B = np.pad(A, pad_width=1)
B

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### **Exercise 26**

Transform the following array

[[ 0, 0, 0, 0, 0, 0],<br>
[ 0, 0, 0, 0, 0, 0],<br>
[ 0, 0, 0, 0, 0, 0],<br>
[ 0, 0, 0, 0, 0, 0],<br>
[ 0, 0, 0, 0, 0, 0],<br>
[ 0, 0, 0, 0, 0, 0]] <br>

To the following array

[[10, 0, 10, 0, 10, 0],<br>
[ 5, 0, 5, 0, 5, 0],<br>
[ 10, 0, 10, 0, 10, 0],<br>
[ 5, 0, 5, 0, 5, 0],<br>
[ 10, 0, 10, 0, 10, 0],<br>
[ 5, 0, 5, 0, 5, 0]] <br>


In [27]:
A = np.zeros(shape=(6,6))
A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [31]:
A[::2, ::2] = 10  #row_start::row_interval, column_start::column_interval
A[1::2, ::2] = 5
A

array([[10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.],
       [10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.],
       [10.,  0., 10.,  0., 10.,  0.],
       [ 5.,  0.,  5.,  0.,  5.,  0.]])

[Slicing](https://regenerativetoday.com/indexing-and-slicing-of-1d-2d-and-3d-arrays-using-numpy/)

### **Exercise 27**

Combine the following arrays into one.

1. np.arange(12).reshape(-1, 4)
2. [[ 4,  3,  7,  2],<br>[ 0,  5,  2,  6],<br>

In [36]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
B = np.array([[4, 3, 7, 2],
             [0, 5, 2, 6]])
B

array([[4, 3, 7, 2],
       [0, 5, 2, 6]])

In [40]:
C = np.append(A, B, axis=0)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### **Exercise 28**


Consider the following two arrays.

1. np.arange(8).reshape(-1, 4)
2. [[ 9,  10,  11,  3],<br>[ 2,  8,  0,  9],<br>

Extract the same elements (intersection) of the arrays

In [45]:
A = np.arange(8).reshape(-1, 4)
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [46]:
B = np.array([[9, 10, 11, 3],
             [2, 8, 0, 9]])
B

array([[ 9, 10, 11,  3],
       [ 2,  8,  0,  9]])

In [47]:
np.intersect1d(A, B)

array([0, 2, 3])

### **Exercise 29**

Consider the following array

[[5, 1, 2, 1, 2],<br>
[9, 1, 9, 7, 5],<br>
[4, 1, 5, 7, 9]]

Extract all unique values of this array

In [50]:
A = np.random.randint(low=1, high=10, size=(3, 5))

In [52]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])

In [53]:
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### **Exercise 30**

Consider the following array

[[0.4, 0.3, 0.3],<br>
[0.1, 0.1, 0.8],<br>
[0.2, 0.5, 0.3]]

Return a list of indexes with maximum values for each **row** from this array

In [56]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])

In [61]:
np.argmax(A, axis=1)

array([0, 2, 1])